import type { GadsCampaign, GadsAdGroup, GadsAd } from "@/lib/types";

export const MOCK_CAMPAIGNS: GadsCampaign[] = [
  {
    id: "8374619250",
    name: "Summer Sale 2026",
    status: "ENABLED",
    advertisingChannelType: "SEARCH",
    biddingStrategyType: "TARGET_CPA",
    budget: {
      amountMicros: 50_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: true,
      targetSearchNetwork: true,
      targetContentNetwork: false,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    trackingUrlTemplate:
      "https://tracking.example.com?campaign={campaignid}",
    accountId: "123-456-7890",
    accountName: "Acme Corp",
  },
  {
    id: "5029173846",
    name: "Brand Awareness Q3",
    status: "ENABLED",
    advertisingChannelType: "DISPLAY",
    biddingStrategyType: "TARGET_IMPRESSION_SHARE",
    budget: {
      amountMicros: 100_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: false,
      targetSearchNetwork: false,
      targetContentNetwork: true,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-07-01",
    accountId: "123-456-7890",
    accountName: "Acme Corp",
  },
  {
    id: "1948362057",
    name: "Product Launch - Widget Pro",
    status: "PAUSED",
    advertisingChannelType: "SEARCH",
    biddingStrategyType: "MAXIMIZE_CONVERSIONS",
    budget: {
      amountMicros: 75_000_000,
      totalAmountMicros: 2_250_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: true,
      targetSearchNetwork: true,
      targetContentNetwork: false,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-03-01",
    endDate: "2026-05-31",
    accountId: "987-654-3210",
    accountName: "Widget Inc",
  },
  {
    id: "6715028394",
    name: "Holiday Shopping 2026",
    status: "ENABLED",
    advertisingChannelType: "SHOPPING",
    biddingStrategyType: "TARGET_ROAS",
    budget: {
      amountMicros: 200_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: true,
      targetSearchNetwork: true,
      targetContentNetwork: false,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-10-01",
    endDate: "2026-12-31",
    accountId: "123-456-7890",
    accountName: "Acme Corp",
  },
  {
    id: "3082947561",
    name: "Video Reach - Summer Vibes",
    status: "ENABLED",
    advertisingChannelType: "VIDEO",
    biddingStrategyType: "MANUAL_CPV",
    budget: {
      amountMicros: 30_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: false,
      targetSearchNetwork: false,
      targetContentNetwork: true,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-06-15",
    accountId: "987-654-3210",
    accountName: "Widget Inc",
  },
  {
    id: "9451637280",
    name: "Performance Max - All Products",
    status: "ENABLED",
    advertisingChannelType: "PERFORMANCE_MAX",
    biddingStrategyType: "MAXIMIZE_CONVERSION_VALUE",
    budget: {
      amountMicros: 150_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: true,
      targetSearchNetwork: true,
      targetContentNetwork: true,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-01-01",
    urlExpansionOptOut: false,
    accountId: "123-456-7890",
    accountName: "Acme Corp",
  },
  {
    id: "4263819075",
    name: "Retargeting - Cart Abandoners",
    status: "ENABLED",
    advertisingChannelType: "DISPLAY",
    biddingStrategyType: "TARGET_CPA",
    budget: {
      amountMicros: 40_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: false,
      targetSearchNetwork: false,
      targetContentNetwork: true,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-02-01",
    accountId: "123-456-7890",
    accountName: "Acme Corp",
  },
  {
    id: "7580194362",
    name: "Lead Gen - Enterprise SaaS",
    status: "ENABLED",
    advertisingChannelType: "SEARCH",
    biddingStrategyType: "MAXIMIZE_CONVERSIONS",
    budget: {
      amountMicros: 250_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: true,
      targetSearchNetwork: true,
      targetContentNetwork: false,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-01-15",
    trackingUrlTemplate: "https://tracking.widget.inc?campaign={campaignid}&source=google",
    finalUrlSuffix: "utm_source=google&utm_medium=cpc",
    accountId: "987-654-3210",
    accountName: "Widget Inc",
  },
  {
    id: "2637405918",
    name: "App Install - iOS",
    status: "PAUSED",
    advertisingChannelType: "MULTI_CHANNEL",
    biddingStrategyType: "TARGET_CPA",
    budget: {
      amountMicros: 80_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: true,
      targetSearchNetwork: false,
      targetContentNetwork: true,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    accountId: "987-654-3210",
    accountName: "Widget Inc",
  },
  {
    id: "8194057326",
    name: "Demand Gen - Spring Collection",
    status: "ENABLED",
    advertisingChannelType: "DEMAND_GEN",
    biddingStrategyType: "MAXIMIZE_CONVERSION_VALUE",
    budget: {
      amountMicros: 120_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: false,
      targetSearchNetwork: false,
      targetContentNetwork: true,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-03-01",
    endDate: "2026-05-31",
    accountId: "123-456-7890",
    accountName: "Acme Corp",
  },
  {
    id: "5308261947",
    name: "Local Services - NYC",
    status: "ENABLED",
    advertisingChannelType: "LOCAL_SERVICES",
    biddingStrategyType: "MANUAL_CPC",
    budget: {
      amountMicros: 25_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: true,
      targetSearchNetwork: false,
      targetContentNetwork: false,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-05-01",
    accountId: "987-654-3210",
    accountName: "Widget Inc",
  },
  {
    id: "1746389052",
    name: "Back to School 2026",
    status: "PAUSED",
    advertisingChannelType: "SHOPPING",
    biddingStrategyType: "TARGET_ROAS",
    budget: {
      amountMicros: 180_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: true,
      targetSearchNetwork: true,
      targetContentNetwork: false,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-07-15",
    endDate: "2026-09-15",
    accountId: "123-456-7890",
    accountName: "Acme Corp",
  },
  {
    id: "6927401835",
    name: "Competitor Conquest - Search",
    status: "ENABLED",
    advertisingChannelType: "SEARCH",
    biddingStrategyType: "MANUAL_CPC",
    budget: {
      amountMicros: 60_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: true,
      targetSearchNetwork: true,
      targetContentNetwork: false,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-02-15",
    accountId: "987-654-3210",
    accountName: "Widget Inc",
  },
  {
    id: "3850172694",
    name: "YouTube Pre-Roll - Brand Story",
    status: "ENABLED",
    advertisingChannelType: "VIDEO",
    biddingStrategyType: "MANUAL_CPM",
    budget: {
      amountMicros: 90_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: false,
      targetSearchNetwork: false,
      targetContentNetwork: true,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2026-04-01",
    accountId: "123-456-7890",
    accountName: "Acme Corp",
  },
  {
    id: "7213840569",
    name: "Smart Campaign - Local Bakery",
    status: "REMOVED",
    advertisingChannelType: "SMART",
    biddingStrategyType: "TARGET_SPEND",
    budget: {
      amountMicros: 15_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: true,
      targetSearchNetwork: true,
      targetContentNetwork: true,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2025-11-01",
    endDate: "2026-01-31",
    accountId: "987-654-3210",
    accountName: "Widget Inc",
  },
  {
    id: "4091625738",
    name: "Discovery - New Audiences",
    status: "REMOVED",
    advertisingChannelType: "DISCOVERY",
    biddingStrategyType: "MAXIMIZE_CONVERSIONS",
    budget: {
      amountMicros: 55_000_000,
      deliveryMethod: "STANDARD",
      period: "DAILY",
    },
    networkSettings: {
      targetGoogleSearch: false,
      targetSearchNetwork: false,
      targetContentNetwork: true,
      targetPartnerSearchNetwork: false,
    },
    geoTargetTypeSetting: {
      positiveGeoTargetType: "PRESENCE_OR_INTEREST",
      negativeGeoTargetType: "PRESENCE",
    },
    startDate: "2025-09-01",
    endDate: "2025-12-31",
    accountId: "123-456-7890",
    accountName: "Acme Corp",
  },
];

export const MOCK_AD_GROUPS: GadsAdGroup[] = [
  {
    id: "ag-1",
    campaignId: "8374619250",
    name: "Brand Keywords",
    status: "ENABLED",
    type: "SEARCH_STANDARD",
    cpcBidMicros: 2_500_000,
    targetCpaMicros: 15_000_000,
  },
  {
    id: "ag-2",
    campaignId: "8374619250",
    name: "Generic Keywords",
    status: "ENABLED",
    type: "SEARCH_STANDARD",
    cpcBidMicros: 3_000_000,
    targetCpaMicros: 20_000_000,
  },
  {
    id: "ag-3",
    campaignId: "8374619250",
    name: "Competitor Keywords",
    status: "PAUSED",
    type: "SEARCH_STANDARD",
    cpcBidMicros: 4_000_000,
  },
  {
    id: "ag-4",
    campaignId: "5029173846",
    name: "In-Market Audiences",
    status: "ENABLED",
    type: "DISPLAY_STANDARD",
    cpmBidMicros: 5_000_000,
  },
  {
    id: "ag-4b",
    campaignId: "5029173846",
    name: "Retargeting Visitors",
    status: "ENABLED",
    type: "DISPLAY_STANDARD",
    cpmBidMicros: 8_000_000,
  },
  {
    id: "ag-4c",
    campaignId: "5029173846",
    name: "Lookalike Audiences",
    status: "ENABLED",
    type: "DISPLAY_STANDARD",
    cpmBidMicros: 6_000_000,
  },
  {
    id: "ag-5",
    campaignId: "1948362057",
    name: "Widget Pro - Exact",
    status: "ENABLED",
    type: "SEARCH_STANDARD",
    cpcBidMicros: 3_500_000,
    targetCpaMicros: 12_000_000,
  },
  {
    id: "ag-6",
    campaignId: "3082947561",
    name: "Summer Vibes - Skippable",
    status: "ENABLED",
    type: "VIDEO_TRUE_VIEW_IN_STREAM",
    cpvBidMicros: 100_000,
  },
];

export const MOCK_ADS: GadsAd[] = [
  {
    id: "ad-1",
    adGroupId: "ag-1",
    type: "RESPONSIVE_SEARCH_AD",
    headlines: [
      "Summer Sale - Up to 50% Off",
      "Shop Now & Save Big",
      "Free Shipping Today",
      "Best Deals of the Season",
    ],
    descriptions: [
      "Get amazing summer deals on all products. Shop our collection today.",
      "Free shipping on orders over $50. Limited time offer!",
    ],
    finalUrls: ["https://acme.com/summer-sale"],
  },
  {
    id: "ad-2",
    adGroupId: "ag-1",
    type: "RESPONSIVE_SEARCH_AD",
    headlines: [
      "Acme Summer Collection",
      "New Arrivals - Summer 2026",
      "Trending Now",
    ],
    descriptions: [
      "Discover our latest summer arrivals. Stylish, affordable, delivered fast.",
    ],
    finalUrls: ["https://acme.com/summer-collection"],
  },
  {
    id: "ad-3",
    adGroupId: "ag-2",
    type: "RESPONSIVE_SEARCH_AD",
    headlines: [
      "Buy Products Online",
      "Quality Guaranteed",
      "Fast Delivery Available",
    ],
    descriptions: [
      "Shop top-quality products at competitive prices. Satisfaction guaranteed or your money back.",
    ],
    finalUrls: ["https://acme.com/products"],
  },
  {
    id: "ad-4",
    adGroupId: "ag-4",
    type: "RESPONSIVE_DISPLAY_AD",
    headlines: ["Brand Awareness Display"],
    descriptions: ["Experience the Acme difference."],
    finalUrls: ["https://acme.com"],
  },
  {
    id: "ad-4b",
    adGroupId: "ag-4",
    type: "RESPONSIVE_DISPLAY_AD",
    headlines: ["Acme — Built for You"],
    descriptions: ["Quality products that make a difference. Discover Acme today."],
    finalUrls: ["https://acme.com/about"],
  },
  {
    id: "ad-4c",
    adGroupId: "ag-4b",
    type: "RESPONSIVE_DISPLAY_AD",
    headlines: ["Come Back for More"],
    descriptions: ["We saved your cart. Complete your order and get 10% off."],
    finalUrls: ["https://acme.com/cart-recovery"],
  },
  {
    id: "ad-4d",
    adGroupId: "ag-4b",
    type: "RESPONSIVE_DISPLAY_AD",
    headlines: ["Exclusive Return Offer"],
    descriptions: ["Welcome back! Enjoy free shipping on your next purchase."],
    finalUrls: ["https://acme.com/welcome-back"],
  },
  {
    id: "ad-4e",
    adGroupId: "ag-4c",
    type: "RESPONSIVE_DISPLAY_AD",
    headlines: ["Discover Acme Products"],
    descriptions: ["People like you love Acme. See what the buzz is about."],
    finalUrls: ["https://acme.com/discover"],
  },
  {
    id: "ad-5",
    adGroupId: "ag-5",
    type: "RESPONSIVE_SEARCH_AD",
    headlines: [
      "Widget Pro - Revolutionary",
      "Try Widget Pro Free",
      "Widget Pro - Best in Class",
    ],
    descriptions: [
      "The all-new Widget Pro. Faster, smarter, better. Try it free for 30 days.",
    ],
    finalUrls: ["https://widget.inc/pro"],
  },
  {
    id: "ad-6",
    adGroupId: "ag-6",
    type: "VIDEO_AD",
    headlines: ["Summer Vibes"],
    descriptions: ["Feel the summer with Widget Inc."],
    finalUrls: ["https://widget.inc/summer"],
  },
];
